version: '2.0'
services:
  java:
    image: java
    working_dir: /home/suporte/devops/repositorio
    environment:
     JVM_OPTS: -Xmx3200m
     TERM: dumb
     key: v1-dependencies-{{ checksum "build.gradle" }}
     run: gradle dependencies
     paths: /home/suporte/devops/.gradle
     key: v1-dependencies-{{ checksum "build.gradle" }}
     run: gradle test